apiVersion: v1
kind: Template
parameters:
  - name: APP_NAME
    description: The name for the application
    displayName: Application Name
    required: true
    value: fubar
  - name: WELCOME_IMAGE_NAME
    description: The Welcome App's image name
    displayName: Image Name
    required: true
    value: fabric8/launcher-creator-welcome-app
  - name: WELCOME_IMAGE_TAG
    description: The Welcome App's image tag
    displayName: Image Tag
    required: true
    value: latest
  - name: WELCOME_APP_CONFIG
    description: The configuration for the welcome app
    displayName: Welcome App Configuration
    required: true
    value: >-
      {"application":"fubar","parts":[{"shared":{"runtime":{"name":"vertx"},"maven":{"groupId":"org.openshift.appgen","artifactId":"my-app","version":"1.0.0"}},"extra":{"runtimeInfo":{"image":"registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift","enumInfo":{"id":"vertx","name":"Vert.x","icon":"data:image/svg+xml;charset=utf8,%3Csvg
      xmlns='http://www.w3.org/2000/svg' viewBox='0 0 640 280'%3E%3Cpath
      fill='%23022B37' d='M107 170.8L67.7 72H46.9L100 204h13.9L167 72h-20.4zm64
      33.2h80v-20h-61v-37h60v-19h-60V91h61V72h-80zm180.1-90.7c0-21-14.4-42.3-43.1-42.3h-48v133h19V91h29.1c16.1
      0 24 11.1 24 22.4 0 11.5-7.9 22.6-24 22.6H286v9.6l48 58.4h24.7L317
      154c22.6-4 34.1-22 34.1-40.7m56.4 90.7v-1c0-6 1.7-11.7
      4.5-16.6V91h39V71h-99v20h41v113h14.5z'/%3E%3Cpath fill='%23623C94' d='M458
      203c0-9.9-8.1-18-18-18s-18 8.1-18 18 8.1 18 18 18 18-8.1 18-18M577.4
      72h-23.2l-27.5 37.8L499.1 72h-40.4c12.1 16 33.6 46.8 47.8 66.3l-37 50.9c2
      4.2 3.1 8.9 3.1 13.8v1H499l95.2-132h-16.8zm-19.7 81.5l-20.1 27.9 16.5
      22.6h40.2c-9.6-13.7-24-33.3-36.6-50.5z'/%3E%3C/svg%3E","description":"A
      tool-kit for building reactive applications on the
      JVM.","metadata":{"language":"java"}},"service":"fubar-backend","route":"fubar-backend"},"category":"backend"},"capabilities":[{"module":"database","props":{"databaseType":"postgresql"},"extra":{"category":"backend","databaseInfo":{"image":"postgresql","service":"fubar-backend-database-bind"},"sourceMapping":{"dbEndpoint":"backend/src/main/java/io/openshift/booster/database/CrudApplication.java"}}},{"module":"rest","props":{},"extra":{"category":"backend","sourceMapping":{"greetingEndpoint":"backend/src/main/java/io/openshift/booster/http/HttpApplication.java"}}}],"subFolderName":"backend"},{"shared":{"framework":{"name":"angular"}},"extra":{"frameworkInfo":{"image":"nodeshift/centos7-s2i-web-app","enumInfo":{"id":"angular","name":"Angular","description":"A
      declarative JavaScript framework for building user
      interfaces.","icon":"data:image/svg+xml,%3c%3fxml version='1.0'
      encoding='utf-8'%3f%3e %3c!-- Generator: Adobe Illustrator 19.1.0%2c SVG
      Export Plug-In . SVG Version: 6.00 Build 0) --%3e %3csvg version='1.1'
      id='Layer_1' xmlns='http://www.w3.org/2000/svg'
      xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' viewBox='0 0
      250 250' style='enable-background:new 0 0 250 250%3b'
      xml:space='preserve'%3e %3cstyle type='text/css'%3e
      .st0%7bfill:%23DD0031%3b%7d .st1%7bfill:%23C3002F%3b%7d
      .st2%7bfill:white%3b%7d %3c/style%3e %3cg%3e %3cpolygon class='st0'
      points='125%2c30 125%2c30 125%2c30 31.9%2c63.2 46.1%2c186.3 125%2c230
      125%2c230 125%2c230 203.9%2c186.3 218.1%2c63.2 '/%3e %3cpolygon
      class='st1' points='125%2c30 125%2c52.2 125%2c52.1 125%2c153.4 125%2c153.4
      125%2c230 125%2c230 203.9%2c186.3 218.1%2c63.2 125%2c30 '/%3e %3cpath
      class='st2'
      d='M125%2c52.1L66.8%2c182.6h0h21.7h0l11.7-29.2h49.4l11.7%2c29.2h0h21.7h0L125%2c52.1L125%2c52.1L125%2c52.1L125%2c52.1
      L125%2c52.1z M142%2c135.4H108l17-40.9L142%2c135.4z'/%3e %3c/g%3e
      %3c/svg%3e","metadata":{"language":"javascript"}},"service":"fubar-frontend","route":"fubar-frontend"},"category":"frontend"},"capabilities":[{"module":"web-app","props":{},"extra":{"category":"frontend"}}],"subFolderName":"frontend"},{"shared":{},"extra":{"category":"support"},"capabilities":[{"module":"welcome","props":{},"extra":{"category":"support"}}],"subFolderName":"support"}]}
  - name: FRONTEND_SERVICE_NAME
    description: The frontend service name for the welcome app
    displayName: Frontend service name
    required: true
    value: fubar-frontend
  - name: BACKEND_SERVICE_NAME
    description: The backend service name for the welcome app
    displayName: Backend service name
    required: true
    value: fubar-backend
  - name: SOURCE_REPOSITORY_PROVIDER
    description: The source repository provider
    displayName: Source Provider
    value: GitHub
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
  - name: OPENSHIFT_CONSOLE_URL
    description: The OpenShift Console URL for the application
    displayName: OpenShift Console URL
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: welcome
      labels:
        app: '${APP_NAME}'
        creatorCategory: support
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${WELCOME_IMAGE_TAG}'
          from:
            kind: DockerImage
            name: '${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}'
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: welcome
      labels:
        app: '${APP_NAME}'
        creatorCategory: support
    spec:
      replicas: 1
      selector:
        app: '${APP_NAME}'
        deploymentconfig: welcome
      strategy:
        resources: {}
      template:
        metadata:
          labels:
            app: '${APP_NAME}'
            deploymentconfig: welcome
        spec:
          containers:
            - image: '${WELCOME_IMAGE_NAME}:${WELCOME_IMAGE_TAG}'
              name: welcome
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 10m
                  memory: 8M
                limits:
                  cpu: 50m
                  memory: 80Mi
              env:
                - name: WELCOME_APP_CONFIG
                  value: '${WELCOME_APP_CONFIG}'
                - name: OPENSHIFT_CONSOLE_URL
                  value: '${OPENSHIFT_CONSOLE_URL}'
                - name: SOURCE_REPOSITORY_PROVIDER
                  value: '${SOURCE_REPOSITORY_PROVIDER}'
                - name: SOURCE_REPOSITORY_URL
                  value: '${SOURCE_REPOSITORY_URL}'
                - name: FRONTEND_SERVICE_NAME
                  value: '${FRONTEND_SERVICE_NAME}'
                - name: BACKEND_SERVICE_NAME
                  value: '${BACKEND_SERVICE_NAME}'
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 10
                timeoutSeconds: 10
                periodSeconds: 20
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 10
                timeoutSeconds: 10
                periodSeconds: 20
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - welcome
            from:
              kind: ImageStreamTag
              name: 'welcome:${WELCOME_IMAGE_TAG}'
          type: ImageChange
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: welcome
      labels:
        app: '${APP_NAME}'
        creatorCategory: support
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: '${APP_NAME}'
        deploymentconfig: welcome
  - apiVersion: v1
    kind: Route
    metadata:
      name: welcome
      labels:
        app: '${APP_NAME}'
        creatorCategory: support
      annotations:
        console.alpha.openshift.io/overview-app-route: 'true'
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: welcome
